### ISSUE TITLE
Customize Wrap Panel?

### ISSUE THREAD

**Issue by HeadMonitor** [egorozh/Tabalonia#10]
Hello, how would one customize the Wrap Panel of Tabalonia? Normally you would be able to change it's color with:
```
<Style Selector="WrapPanel">
        <Setter Property="Background" Value="Blue" />
</Style>
```

Thanks in advance!

**Comment by egorozh** [comment]
I don't understand which WrapPanel you want to customize. Can you send me a screenshot?

**Comment by HeadMonitor** [comment]
![image](https://github.com/egorozh/Tabalonia/assets/62361708/987b95ad-3b75-404a-90f4-8b03d4ecf2b3)

Behind the + for example. Screenshot is from the Demo Gif.

**Comment by egorozh** [comment]
> ![image](https://user-images.githubusercontent.com/62361708/279717772-987b95ad-3b75-404a-90f4-8b03d4ecf2b3.png)
> 
> Behind the + for example. Screenshot is from the Demo Gif.

![image](https://github.com/egorozh/Tabalonia/assets/37664492/d80c9e9a-15ee-4b4d-b3e7-22c618ccaa40)

**Comment by HeadMonitor** [comment]
![image](https://github.com/egorozh/Tabalonia/assets/62361708/f98064e5-32ca-45a5-9f4d-cc55f7c89275)
What about the rest of the background? Behind the + and behind the tab?

**Comment by egorozh** [comment]
You can create your own style. Tabalonia.Demo has an example of hosting your own theme (Styles/MyTheme.axaml)
