### ISSUE TITLE
[Feature Request] Navigation buttons

### ISSUE THREAD

**Issue by G012481632** [egorozh/Tabalonia#12]
First of all, nice work so far !

Currently if a lot of tabs exist or the screen display is not very high in pixels (eg a touchscreen on a raspberry pi - yes we go everywhere these days with c# ! Hallelujah Avalonia), the tabs get too small and are no longer readable and that is a petty.

It would be a major upgrade for the system if you could set a 'minimal width' (in xaml for instance, one width used by all tabs should be fine) for the tab and if this results in tabs 'going of the screen', a navigation (button with arrow left or right, depending on the current position of the tabs on the screen) option would just be the cherry on the cake !

I'm a great fan of Dock.Avalonia and they did a fantastic job (not so well on the navigation of the tabs as such :) ), but in my humble opinion, 95% of the applications do not need a docking solution. A lot can be done with a grid, splitters and a good tab control. Yes, a lot of apps benefit from just a good tab control like yours, without all the bells and whistles of the more complex systems ! So keep up the good work, it is very much appreciated !

**Comment by egorozh** [comment]
Thank you very much for your nice words.

In this case, I think I’ll do it like in Google Chrome: show tabs selectively so that their number meets the minimum width. I don't like the idea of ​​adding arrow buttons)

**Comment by G012481632** [comment]
@egorozh I suppose you refer to tab scrolling ? That in combination with the min width of the tabs, looks great and indeed, no extra buttons required !

Nice, looking forward to the result !
