### ISSUE TITLE
Tabalonia Licence

### ISSUE THREAD

**Issue by BobLd** [egorozh/Tabalonia#13]
Hi, thanks a lot for the great project!

Under which licence is the package released? I could not find any licence file in the repos... Unless I missed it, it's worth adding a LICENCE file so that people (me included!) are confident using the library in there project.

FYI, I see Dragablz is MIT

Thanks a lot again!

**Comment by egorozh** [comment]
Hi) 

I added MIT license

**Comment by BobLd** [comment]
That's amazing! Thanks for that
