### ISSUE TITLE
Empty zone

### ISSUE THREAD

**Issue by BelousovSL** [egorozh/Tabalonia#19]
Hi, thanks for the good control. However, there is one question, I am very new, most likely I am doing something wrong. In the test example, I have a certain unfilled area. I'm attaching a screenshot. 

Thank you.
![TabaloniaQuestion](https://github.com/user-attachments/assets/c6b10ace-85b3-4553-9de8-92a5d714662c)

**Comment by egorozh** [comment]
Hi!

I just didn't support Linux)
```csharp
public static readonly StyledProperty<double> LeftThumbWidthProperty =
        AvaloniaProperty.Register<TabsControl, double>(nameof(LeftThumbWidth),
            defaultValue: OperatingSystem.IsWindows()
                ? WindowsDefaultLeftThumbWidth
                : MacOsDefaultLeftThumbWidth);
```
You can override the `LeftThumbWidth` parameter for the `Tabcontrol`:
```csharp
public partial class MainWindow : Window
{
    public MainWindow()
    {
        InitializeComponent();

        this.Find<TabsControl>("TabsControl")!.LeftThumbWidth = OperatingSystem.IsMacOS() ? 80 : 4;
    }
}
```

In the next version, I will correct this point - I will indent it as in Windows.

**Comment by BelousovSL** [comment]
Yes, that's what I needed.  I will try to integrate your control into my project. 
Thank you.
