### ISSUE TITLE
Idea 💡 

### ISSUE THREAD

**Issue by timunie** [egorozh/Tabalonia#2]
cosider to add this lib to: https://github.com/AvaloniaCommunity/awesome-avalonia 

Btw: Looks really promising to me. Thank you for your efforts ❤️

**Comment by egorozh** [comment]
Thanks for the idea. I'll make a PR there.

**Comment by egorozh** [comment]
Created PR  - https://github.com/AvaloniaCommunity/awesome-avalonia/pull/111
