### ISSUE TITLE
❓ Question  

### ISSUE THREAD

**Issue by marcosgerene** [egorozh/Tabalonia#3]
Is there anyway to make the first tab static? 

I mean, I want the first tab to not being able to be closed/replaced... 

The idea is something like this:

![image](https://github.com/egorozh/Tabalonia/assets/15945003/f39318a4-eff1-4724-b35e-155b5e9f46e0)

The first page is the application's home.

**Comment by egorozh** [comment]
not implemented yet=)

**Comment by marcosgerene** [comment]
Is this feature in your roadmap anyway?

**Comment by egorozh** [comment]
> Is this feature in your roadmap anyway?

I added FixedHeaderCount property in last version)
