### ISSUE TITLE
Theme does not respect RequestedThemeVariant

### ISSUE THREAD

**Issue by derekantrican** [egorozh/Tabalonia#5]
It looks like the dark theme is hardcoded: https://github.com/egorozh/Tabalonia/blob/develop/Tabalonia/Themes/FluentTheme.cs#L28

In my application, I have `RequestedThemeVariant="Light"` (which will be controlled by a user setting later). However, Tabalonia seems to be only dark theme (see below). Can this be be changed to reflect the parent `RequestedThemeVariant`? If not, how do I configure Tabalonia's theme as well?

![image](https://github.com/egorozh/Tabalonia/assets/1558019/54d9fb0d-6123-4557-ac55-464b0f90360c)

**Comment by egorozh** [comment]
I didn't support the light theme. I'll do it soon)

**Comment by egorozh** [comment]
Added new Fluent theme with supporting light theme. Old theme renamed to "Custom".
Also, an example of using your theme has been added to the demo.
![image](https://github.com/egorozh/Tabalonia/assets/37664492/c4c959e9-a752-4779-9261-976d25bef7bd)
