### ISSUE TITLE
Items component

### ISSUE THREAD

**Issue by marcosgerene** [egorozh/Tabalonia#7]
I want to draw some tabs without use ItemSource, how to do this? What is the item component?

![image](https://github.com/egorozh/Tabalonia/assets/15945003/6d24cfb9-05eb-42b2-b971-0ef01ffaa0db)

![image](https://github.com/egorozh/Tabalonia/assets/15945003/cf65dbc6-fc6c-45f7-b5cb-f062282a64af)

**Comment by egorozh** [comment]
This style is not supported. 

You can use like
![image](https://github.com/egorozh/Tabalonia/assets/37664492/13b6d864-00fc-4e0a-8c02-4f3290dda244)

but it's bad working - after dragged tab, tab redraw to initial state=(

**Comment by marcosgerene** [comment]
Thanks @egorozh
