### ISSUE TITLE
No Tabs Appearing

### ISSUE THREAD

**Issue by HeadMonitor** [egorozh/Tabalonia#8]
Hello, as per the Tabalonia example I have tried to integrate it into my application. Problem is that no tabs appear.
My repository: https://github.com/ScreenCrowStudios/CrowEngine

Files that follow the example: https://github.com/ScreenCrowStudios/CrowEngine/blob/master/CrowEngineUI/ViewModels/TabItemViewModel.cs
https://github.com/ScreenCrowStudios/CrowEngine/blob/master/CrowEngineUI/ViewModels/MainViewModel.cs
https://github.com/ScreenCrowStudios/CrowEngine/blob/master/CrowEngineUI/Views/BottomTabs.axaml

Thanks in advance!

**Comment by egorozh** [comment]
Have you added the theme on App.xaml?
![image](https://github.com/egorozh/Tabalonia/assets/37664492/0cc64b04-0eca-4bdb-a09a-79a7b9c9738d)

**Comment by HeadMonitor** [comment]
Thank you for your reply. It seems that was the issue! Apologies for the confusion. One more thing I am not sure how to fix is this:
![image](https://github.com/egorozh/Tabalonia/assets/62361708/623fd2b9-74be-4ac6-bed0-c524695cec96)

With the same code no tabs appear. Only the plus sign. Any idea why that might be happening?

**Comment by egorozh** [comment]
This is a bug) I did not test the lack of tabs, since by default the window closes after closing the last tab.

I'll try to fix it soon

**Comment by HeadMonitor** [comment]
i see what you are referring to but for me there were no tabs to begin with.

**Comment by G012481632** [comment]
> This is a bug) I did not test the lack of tabs, since by default the window closes after closing the last tab.

@egorozh  Can you make the closing of the window optional ? Like @HeadMonitor  I have no tabs half of the time (both at startup and during runtime)

**Comment by egorozh** [comment]
> > This is a bug) I did not test the lack of tabs, since by default the window closes after closing the last tab.
> 
> @egorozh Can you make the closing of the window optional ? Like @HeadMonitor I have no tabs half of the time (both at startup and during runtime)

It's working now. You can set closed action like:
![image](https://github.com/egorozh/Tabalonia/assets/37664492/04627f14-f75a-4912-9df7-1380d21d4589)

**Comment by egorozh** [comment]
> Thank you for your reply. It seems that was the issue! Apologies for the confusion. One more thing I am not sure how to fix is this: ![image](https://user-images.githubusercontent.com/62361708/278597277-623fd2b9-74be-4ac6-bed0-c524695cec96.png)
> 
> With the same code no tabs appear. Only the plus sign. Any idea why that might be happening?

Fixed in 0.9.12
![image](https://github.com/egorozh/Tabalonia/assets/37664492/f83166db-ee81-47e5-959d-eb731d5c2095)

**Comment by HeadMonitor** [comment]
https://github.com/ScreenCrowStudios/CrowEngine/blob/master/CrowEngineProjectManager/ViewModels/MainWindowTabsViewModel.cs
https://github.com/ScreenCrowStudios/CrowEngine/blob/master/CrowEngineProjectManager/ViewModels/TabItemViewModel.cs
https://github.com/ScreenCrowStudios/CrowEngine/blob/master/CrowEngineProjectManager/Views/MainWindow.axaml

Hello, thank you for your replies. I have followed the demo but I cannot figure out how to add tabs. No tabs appear at all. Any idea why this is happening?

**Comment by egorozh** [comment]
> https://github.com/ScreenCrowStudios/CrowEngine/blob/master/CrowEngineProjectManager/ViewModels/MainWindowTabsViewModel.cs https://github.com/ScreenCrowStudios/CrowEngine/blob/master/CrowEngineProjectManager/ViewModels/TabItemViewModel.cs https://github.com/ScreenCrowStudios/CrowEngine/blob/master/CrowEngineProjectManager/Views/MainWindow.axaml
> 
> Hello, thank you for your replies. I have followed the demo but I cannot figure out how to add tabs. No tabs appear at all. Any idea why this is happening?

ViewModel not setted to DataContext. Try like this:
![image](https://github.com/egorozh/Tabalonia/assets/37664492/ddd14395-5590-478c-a902-85c51e657c5c)

**Comment by HeadMonitor** [comment]
Thanks a lot, that worked!
